### ISSUE TITLE
Developing CI pipeline to run validator and publish model metrics on Equinix

### ISSUE THREAD

**Issue by husky-parul** [sustainable-computing-io/kepler-metal-ci#11]
Currently there are workflows in the repo [https://github.com/sustainable-computing-io/kepler-metal-ci/tree/main](http://example.com/) to create equinix runners. 

Create workflow that does the following:

On equinix BM capture metrics using validator module
On equinix VM capture metrics using validator module
Compare the BM vs VM metrics and compute delta
Report delta

**Comment by SamYuan1990** [comment]
I suppose kepler action should be considered to integrate with this repo.

**Comment by rootfs** [comment]
@SamYuan1990 @husky-parul the valiator pipeline is [here](https://github.com/sustainable-computing-io/kepler-metal-ci/blob/main/.github/workflows/equinix_metal_flow.yml#L63). The VM/BM metrics report needs to be produced in the [new](https://github.com/sustainable-computing-io/kepler/pull/1489) validator. 

cc @sthaha @KaiyiLiu1234

**Comment by rootfs** [comment]
The first validation CI run is [here](https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/9425384298/job/25967054199). The MSE is inf at the moment but we are getting there.

**Comment by rootfs** [comment]
validation test results are now published by ci
https://github.com/sustainable-computing-io/kepler-metal-ci/commit/f9dfad7714b646a0d12fce7edf8609f5c986711e
