### ISSUE TITLE
Workflow fails to copy artifacts to the existing folder inside docs

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-metal-ci#230]
When a workflow tries to move the artifacts from the `/tmp` to the docs folder which already contains the artifacts for the same date it fails at the point where it tries to move. This should be fixed as the workflows that are triggered even if there are some artifacts present for the same date should create a subfolder and add the required artifacts in that directory.

Sample CI failure run for reference: https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/10790840217/job/29927359981#step:5:3494

Here the docs directory already contained `docs/validation/2024-09-10/validator-v0.7.11-216-gdaa0a635`. If another run is called it should be placed under the docs directory something like this:
```
docs/validation/2024-09-10/validator-v0.7.11-216-gdaa0a635-run-1
```

**Comment by KaiyiLiu1234** [comment]
Another way this can be done is with timestamps. so either docs/validation/2024-09-10:H:M:S or docs/validation/ocs/validation/2024-09-10/validator-v0.7.11-216-gdaa0a635-H:M:S. Essentially with the current setup of using strictly date we can't upload multiple a day which should not be an issue as workflows are run daily but in the future the rate when we run workflows can change. Timestamp might give more information.

**Comment by sthaha** [comment]
@vprashar2929 +1 to using timestamps instead of computing the directories. 
While at it, can we also organise the directory to `Y%/%m%d` and create `standalone` and `with-model-server` dirs ?

**Comment by vprashar2929** [comment]
closing as #289 is merged
