### ISSUE TITLE
Create an overall report that captures changes to MSE and MAPE over time

### ISSUE THREAD

**Issue by sthaha** [sustainable-computing-io/kepler-metal-ci#66]
At a minimum, lets have a table such as

 | date | platform - dynamic MSE | platform dyn - MAPE| 
|---|---|---|
| 01/08/2024 | 438.89 | 202|
| 02/08/2024 | 238.89 | 102|

In https://github.com/sustainable-computing-io/kepler-metal-ci/tree/main/docs

**Comment by KaiyiLiu1234** [comment]
I can take this task and incorporate into metal ci.
